/**
 * Build-time image optimizer.
 * Reads the curated PNGs the portfolio actually uses from src/assets,
 * emits sized WebP into public/media, and writes src/media.js with
 * intrinsic dimensions so every <img> can ship explicit width/height (zero CLS).
 *
 * Originals in src/assets are never modified.
 * Runs from `predev` and `build`. Skips work when the WebP is newer than its source.
 */
import sharp from 'sharp';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(root, 'src', 'assets');
const OUT = path.join(root, 'public', 'media');

// Gallery shots: scaled to 880px tall (2x of the 440px frame) preserving aspect.
const GALLERY = [
  'sup-lp-comparison', 'sup-checkout-upsell-mobile', 'sup-progress-rebuycart',
  'sup-quiz-lander-mobile', 'sup-review-slider', 'sup-testimonial-carousel-mobile',
  'blu-hero', 'blu-vs-everyone', 'blu-subscription-widget',
  'blu-product-meta', 'blu-cart-progress-mobile', 'blu-popup-upsell-mobile',
  'bla-cart-upsell',
  'shopdeck-theme', 'shopdeck-cart', 'shopdeck-menu',
  'shopdeck-fetch-cart', 'shopdeck-performance', 'shopdeck-debug',
  'technorv-cart-discounts',
];

// name -> { input, transform(sharpInstance), quality }
const JOBS = [
  ...GALLERY.map((name) => ({
    name,
    input: `${name}.png`,
    pipe: (img) => img.resize({ height: 880, withoutEnlargement: true }),
    quality: 78,
  })),
  // About portrait (sits in a 4/5 box, object-fit: cover)
  { name: 'portrait', input: 'portrait.png', pipe: (img) => img.resize({ width: 900, withoutEnlargement: true }), quality: 82 },
  // Nav avatar (30px, retina) — cropped square from the top of the portrait
  { name: 'avatar', input: 'portrait.png', pipe: (img) => img.resize({ width: 96, height: 96, fit: 'cover', position: 'top' }), quality: 82 },
];

async function mtime(p) {
  try { return (await fs.stat(p)).mtimeMs; } catch { return 0; }
}

async function run() {
  await fs.mkdir(OUT, { recursive: true });
  const manifest = {};
  let built = 0, skipped = 0;

  for (const job of JOBS) {
    const inPath = path.join(SRC, job.input);
    const outPath = path.join(OUT, `${job.name}.webp`);
    const inT = await mtime(inPath);
    if (!inT) { console.warn(`[optimize] missing source: ${job.input} — skipping`); continue; }

    let meta;
    if (await mtime(outPath) > inT) {
      meta = await sharp(outPath).metadata(); // up to date — just read dims
      skipped++;
    } else {
      const info = await job.pipe(sharp(inPath)).webp({ quality: job.quality, effort: 5 }).toFile(outPath);
      meta = { width: info.width, height: info.height };
      built++;
    }
    manifest[job.name] = { src: `/media/${job.name}.webp`, w: meta.width, h: meta.height };
  }

  const body =
    '// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit.\n' +
    'export default ' + JSON.stringify(manifest, null, 2) + ';\n';
  await fs.writeFile(path.join(root, 'src', 'media.js'), body);
  console.log(`[optimize] ${built} built, ${skipped} up-to-date → ${Object.keys(manifest).length} images, src/media.js written`);
}

run().catch((e) => { console.error(e); process.exit(1); });
